### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by marysaka** [MeowDJ/MeowDJ#2]
> Auth (Using passport)
> 
> > [X] Normal Login <
> > [ ] First Login
> > - [X] Username
> > - [X] Password
> > - \- [ ] Age
> > - [X] Gender
> > - [X] Newsletter
> > - [X] Terms of Service

.. WIP

**Comment by jeremylvln** [comment]
First and Last name are not required at all in fact... Just a "Display name" ?

**Comment by jeremylvln** [comment]
Newsletter and Terms of Service done.

**Comment by jeremylvln** [comment]
Gender done

**Comment by jeremylvln** [comment]
This is not about this project anymore.
